rwc:
  sys:
    admin: admin
    environment-home: ${REDIS_WCLIENT_HOME:.}
    db:
      file-path: rediswclient.db
server:
  port: 8080
  servlet:
    path: /
spring:
    banner:
      charset: UTF-8
    datasource:
        name: rediswclient
        type: com.alibaba.druid.pool.DruidDataSource
        #druid相关配置
        druid:
          #监控统计拦截的filters
          filters: stat
          driver-class-name: org.sqlite.JDBC
          #基本属性
          #url: jdbc:sqlite:rediswclient.db
          url: jdbc:sqlite:${rwc.sys.environment-home}/RedisWClient.db
          username:
          password:
          #配置初始化大小/最小/最大
          initial-size: 1
          min-idle: 1
          max-active: 20
          #获取连接等待超时时间
          max-wait: 60000
          #间隔多久进行一次检测，检测需要关闭的空闲连接
          time-between-eviction-runs-millis: 60000
          #一个连接在池中最小生存的时间
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 1
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          #Druid不支持SQLite，必须设置false 与 0 才行
          pool-prepared-statements: false
          max-pool-prepared-statement-per-connection-size: 0
          max-open-prepared-statements: 0
mybatis:
  mapper-locations: classpath:mapper/*.xml
pagehelper:
    helperDialect: sqlite
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check